# Generated by Django 4.2 on 2023-04-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='orderitem',
        ),
    ]
