# Generated by Django 4.2 on 2023-04-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cartitem_quantity_remove_order_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitem',
        ),
    ]
