# Generated by Django 4.2 on 2023-04-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orderitem'),
        ),
    ]
