# Generated by Django 4.2 on 2023-04-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
    ]
