# Generated by Django 4.2 on 2023-04-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_first_name_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='varient',
        ),
    ]
