# Generated by Django 4.2 on 2023-04-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_varient_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app.orderitem'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
