# Generated by Django 4.2 on 2023-04-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_order_orderitem_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.orderitem'),
        ),
    ]
