# Generated by Django 4.2 on 2023-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_orders_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_items',
            field=models.JSONField(null=True),
        ),
    ]
