# Generated by Django 4.2 on 2023-04-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_orders_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_items',
        ),
    ]
