# Generated by Django 4.2 on 2023-04-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_users_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
