# Generated by Django 4.2 on 2023-04-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_orderitem_shipping_remove_orderitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='email',
        ),
        migrations.AddField(
            model_name='shipping',
            name='city',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
