# Generated by Django 4.2 on 2023-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cartitem_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_anonymous',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
