# Generated by Django 4.2 on 2023-04-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_cartitem_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_anonymous',
        ),
    ]
