# Generated by Django 4.2 on 2023-04-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='varient',
            name='stock',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
