# Generated by Django 4.2 on 2023-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_orderitems_is_completed_varient_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('placed', 'Placed'), ('shipped', 'Shipped')], default='confirmed', max_length=20, null=True),
        ),
    ]
