# Generated by Django 4.2 on 2023-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('placed', 'Placed'), ('shipped', 'Shipped'), ('cancel', 'cancel')], default='confirmed', max_length=20, null=True),
        ),
    ]
