# Generated by Django 4.2 on 2023-05-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=20, null=True)),
                ('messages', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
