# Generated by Django 4.2 on 2023-05-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_cancelorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancelOrder',
        ),
    ]
