# Generated by Django 4.2 on 2023-05-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_delete_cancelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='messages',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='option',
            field=models.CharField(blank=True, choices=[('payment_issue', 'payment_issue'), ('address_issue', 'address_issue'), ('quality_issue', 'quality_issue'), ('noissue', 'noissue')], default='noissue', max_length=20, null=True),
        ),
    ]
