# Generated by Django 4.2 on 2023-05-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_orders_messages_orders_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
