# Generated by Django 4.2 on 2023-05-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_cartitem_session_key_orders_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='slug',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
