# Generated by Django 4.2 on 2023-05-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_orders_slug_orderitems_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='slug',
        ),
    ]
