# Generated by Django 4.2 on 2023-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_orderitems_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='reason',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
