# Generated by Django 4.2 on 2023-05-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_orders_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='option',
        ),
    ]
