# Generated by Django 4.2 on 2023-05-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_orders_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='approved',
        ),
    ]
