# Generated by Django 4.2 on 2023-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_orders_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='approved_by',
            field=models.CharField(choices=[('Return_approved', 'Return_approved'), ('Return_Rejected', 'Return_Rejected'), ('Return_request_accepted', 'Return_request_accepted')], default='Return_request_accepted', max_length=30),
        ),
    ]
