# Generated by Django 4.2 on 2023-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_defualt',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
