# Generated by Django 4.2 on 2023-05-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_shipping_is_defualt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='is_defualt',
            new_name='is_default',
        ),
    ]
