# Generated by Django 4.2 on 2023-05-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_rename_is_defualt_shipping_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
