# Generated by Django 4.2 on 2023-05-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_shipping_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='varient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='varient',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='varient',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
