# Generated by Django 4.2 on 2023-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_product_banner_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
